### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by mxucmu** [luta-wolf/ExamRank_42#2]
Hi, 

I see you just pushed a new version of Exam06, and the older version became mini_serv1.c.  Is the older version still working? I mean is it still accepted by 42 system?

Best,
Mingxin

**Comment by luta-wolf** [comment]
Hi 

At the final exam 06 I prepared both versions, the one that went to the archive was new, it seems like other peers passed it and at the same time I had three refusals, so I passed mini_serv.c (accepted the first time) and left it as a working one .
